version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    working_directory: ~/nevamanagement-web
    docker:
      - image: cimg/node:16.13.1-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run test