version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run: 
          name: Build Image
          command: docker build -t nevamanagement-web .
  deploy:
    docker:
      - image: docker:17.05.0-ce-git  
    steps:
      - checkout
      - run:
          name: Deploy Container to Heroku
          command: |
            docker tag nevamanagement-web registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web

workflows:
  heroku_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main