version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  
jobs:
  build:
    working_directory: ~/nevamanagement-web
    docker:
      - image: node:16.13.0-alpine
    steps:
      - checkout
      - run: 
          name: Build Image
          command: docker build -t nevamanagement-web .
  deploy:
    docker:
      - image: cimg/node:16.13.1-browsers
    steps:
      - checkout
      - run:
          name: Deploy Container to Heroku
          command: |
            docker tag nevamanagement-web registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web

workflows:
  heroku_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main