version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  
jobs:
  build:
    working_directory: ~/nevamanagement-web
    docker:
      - image: node:16.13.0
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: 
          name: Build Image
          command: docker build -t nevamanagement-web .
  deploy:
    docker:
      - image: cimg/node:16.13.1-browsers
    steps:
      - checkout
      - run:
          name: Deploy Container to Heroku
          command: |
            docker tag nevamanagement-web registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web

workflows:
  heroku_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main